### ISSUE TITLE
Maintenance Release: PhET-iO Hydrogen API updates

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#1017]
@samreid @kathy-phet @brent-phet @pixelzoom @AgustinVallejo @arouinfar

Hello! And welcome to a horrible MR testing issue. This is for testing https://github.com/phetsims/phet-io/issues/1974 and
supplemental info about things to test can be found in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110.
Please do reach out to me for any questions you may have. Please do the spot check you are used to, and then I have supplied any additional work to spot check below. Thank you!

Please note there is one usage of `launchSimulationulation` in the API documentation home page, but it will be fixed (just not in this batch of RCs.

**acid-base-solutions 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [acid-base-solutions 1.3.2-rc.1](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.2-rc.1/phet/acid-base-solutions_all_phet.html)
- [x] [acid-base-solutions 1.3.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.2-rc.1/phet-io/acid-base-solutions_all_phet-io.html?phetioStandalone)
- [x] [acid-base-solutions 1.3.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.2-rc.1/phet-io/wrappers/studio)
- [x] [acid-base-solutions 1.3.2-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.2-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.2-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [ ] ~Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)~
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**beers-law-lab 1.7** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [beers-law-lab 1.7.8-rc.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.8-rc.1/phet/beers-law-lab_all_phet.html)
- [x] [beers-law-lab 1.7.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.8-rc.1/phet-io/beers-law-lab_all_phet-io.html?phetioStandalone)
- [x] [beers-law-lab 1.7.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.8-rc.1/phet-io/wrappers/studio)
- [x] [beers-law-lab 1.7.8-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.8-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.8-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**calculus-grapher 1.0** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [calculus-grapher 1.0.6-rc.1](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.6-rc.1/phet/calculus-grapher_all_phet.html)
- [x] [calculus-grapher 1.0.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.6-rc.1/phet-io/calculus-grapher_all_phet-io.html?phetioStandalone)
- [x] [calculus-grapher 1.0.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.6-rc.1/phet-io/wrappers/studio)
- [x] [calculus-grapher 1.0.6-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.6-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.6-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [ ] ~Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)~
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**center-and-variability 1.1** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/864, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [center-and-variability 1.1.2-rc.1](https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet/center-and-variability_all_phet.html)
- [x] [center-and-variability 1.1.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet-io/center-and-variability_all_phet-io.html?phetioStandalone)
- [x] [center-and-variability 1.1.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet-io/wrappers/studio)
- [x] [center-and-variability 1.1.2-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [ ] ~Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)~
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

Combo Box patches (to be checked by QA):
- [ ] patch 16: [Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.](https://github.com/phetsims/sun/issues/859#issuecomment-1841866186)
- [x] patch 17: [KeyboardListener bug is likely when listening to 'tab'.](https://github.com/phetsims/sun/issues/864#issuecomment-1863558564)
- [x] patch 18: [focusable bug fix for list box.](https://github.com/phetsims/scenery/issues/1550#issuecomment-1863556922)
- [x] patch 19: [Incorrect default sounds for selecting combo box items](https://github.com/phetsims/sun/issues/861#issuecomment-1863516470)
- [ ] patch 20: [Default sound for ComboBoxListBox does not supports dynamic order and visibility of items.](https://github.com/phetsims/sun/issues/862#issuecomment-1863515037)

**circuit-construction-kit-dc 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [circuit-construction-kit-dc 1.3.9-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.9-rc.1/phet/circuit-construction-kit-dc_all_phet.html)
- [x] [circuit-construction-kit-dc 1.3.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.9-rc.1/phet-io/circuit-construction-kit-dc_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc 1.3.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.9-rc.1/phet-io/wrappers/studio)
- [x] [circuit-construction-kit-dc 1.3.9-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.9-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.9-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**circuit-construction-kit-dc-virtual-lab 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [circuit-construction-kit-dc-virtual-lab 1.3.7-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.7-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.7-rc.1/phet-io/circuit-construction-kit-dc-virtual-lab_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.7-rc.1/phet-io/wrappers/studio)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.7-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.7-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.7-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**concentration 1.7** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [concentration 1.7.8-rc.1](https://phet-dev.colorado.edu/html/concentration/1.7.8-rc.1/phet/concentration_all_phet.html)
- [x] [concentration 1.7.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/concentration/1.7.8-rc.1/phet-io/concentration_all_phet-io.html?phetioStandalone)
- [x] [concentration 1.7.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/concentration/1.7.8-rc.1/phet-io/wrappers/studio)
- [x] [concentration 1.7.8-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/concentration/1.7.8-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/concentration/1.7.8-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**density 1.1** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [density 1.1.5-rc.1](https://phet-dev.colorado.edu/html/density/1.1.5-rc.1/phet/density_all_phet.html)
- [x] [density 1.1.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/density/1.1.5-rc.1/phet-io/density_all_phet-io.html?phetioStandalone)
- [x] [density 1.1.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/density/1.1.5-rc.1/phet-io/wrappers/studio)
- [x] [density 1.1.5-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/density/1.1.5-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/density/1.1.5-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**friction 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [friction 1.6.9-rc.1](https://phet-dev.colorado.edu/html/friction/1.6.9-rc.1/phet/friction_all_phet.html)
- [x] [friction 1.6.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/friction/1.6.9-rc.1/phet-io/friction_all_phet-io.html?phetioStandalone)
- [x] [friction 1.6.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/friction/1.6.9-rc.1/phet-io/wrappers/studio)
- [x] [friction 1.6.9-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/friction/1.6.9-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/friction/1.6.9-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [ ] ~Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)~
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**geometric-optics 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [geometric-optics 1.3.4-rc.1](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet/geometric-optics_all_phet.html)
- [x] [geometric-optics 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/geometric-optics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/wrappers/studio)
- [x] [geometric-optics 1.3.4-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

Combo Box patches (to be checked by QA):
- [x] patch 16: [Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.](https://github.com/phetsims/sun/issues/859#issuecomment-1841866186)
- [x] patch 17: [KeyboardListener bug is likely when listening to 'tab'.](https://github.com/phetsims/sun/issues/864#issuecomment-1863558564)
- [x] patch 18: [focusable bug fix for list box.](https://github.com/phetsims/scenery/issues/1550#issuecomment-1863556922)
- [x] patch 19: [Incorrect default sounds for selecting combo box items](https://github.com/phetsims/sun/issues/861#issuecomment-1863516470)
- [x] patch 20: [Default sound for ComboBoxListBox does not supports dynamic order and visibility of items.](https://github.com/phetsims/sun/issues/862#issuecomment-1863515037)

**geometric-optics-basics 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [geometric-optics-basics 1.3.4-rc.1](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.4-rc.1/phet/geometric-optics-basics_all_phet.html)
- [x] [geometric-optics-basics 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.4-rc.1/phet-io/geometric-optics-basics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics-basics 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.4-rc.1/phet-io/wrappers/studio)
- [x] [geometric-optics-basics 1.3.4-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.4-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

Combo Box patches (to be checked by QA):
- [x] patch 16: [Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.](https://github.com/phetsims/sun/issues/859#issuecomment-1841866186)
- [x] patch 17: [KeyboardListener bug is likely when listening to 'tab'.](https://github.com/phetsims/sun/issues/864#issuecomment-1863558564)
- [x] patch 18: [focusable bug fix for list box.](https://github.com/phetsims/scenery/issues/1550#issuecomment-1863556922)
- [x] patch 19: [Incorrect default sounds for selecting combo box items](https://github.com/phetsims/sun/issues/861#issuecomment-1863516470)
- [x] patch 20: [Default sound for ComboBoxListBox does not supports dynamic order and visibility of items.](https://github.com/phetsims/sun/issues/862#issuecomment-1863515037)

**graphing-quadratics 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [graphing-quadratics 1.3.4-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.4-rc.1/phet/graphing-quadratics_all_phet.html)
- [x] [graphing-quadratics 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.4-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.4-rc.1/phet-io/wrappers/studio)
- [x] [graphing-quadratics 1.3.4-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.4-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**gravity-and-orbits 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974, getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper: phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974, phetmarks-perennial-url: phetsims/phet-io#1974, add readonly for GAO1.6: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [gravity-and-orbits 1.6.16-rc.2](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.16-rc.2/phet/gravity-and-orbits_all_phet.html)
- [x] [gravity-and-orbits 1.6.16-rc.2 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.16-rc.2/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.6.16-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.16-rc.2/phet-io/wrappers/studio)
- [x] [gravity-and-orbits 1.6.16-rc.2 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.16-rc.2/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [ ] ~Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)~
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**greenhouse-effect 1.2** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/864, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [greenhouse-effect 1.2.4-rc.1](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.4-rc.1/phet/greenhouse-effect_all_phet.html)
- [x] [greenhouse-effect 1.2.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.4-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.2.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.4-rc.1/phet-io/wrappers/studio)
- [x] [greenhouse-effect 1.2.4-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.4-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

Combo Box patches (to be checked by QA):
- [x] patch 16: [Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.](https://github.com/phetsims/sun/issues/859#issuecomment-1841866186)
- [x] patch 17: [KeyboardListener bug is likely when listening to 'tab'.](https://github.com/phetsims/sun/issues/864#issuecomment-1863558564)
- [x] patch 18: [focusable bug fix for list box.](https://github.com/phetsims/scenery/issues/1550#issuecomment-1863556922)
- [x] patch 19: [Incorrect default sounds for selecting combo box items](https://github.com/phetsims/sun/issues/861#issuecomment-1863516470)
- [x] patch 20: [Default sound for ComboBoxListBox does not supports dynamic order and visibility of items.](https://github.com/phetsims/sun/issues/862#issuecomment-1863515037)

**molecule-polarity 1.3** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/scenery/issues/1550, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [molecule-polarity 1.3.4-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.4-rc.1/phet/molecule-polarity_all_phet.html)
- [x] [molecule-polarity 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.4-rc.1/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [x] [molecule-polarity 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.4-rc.1/phet-io/wrappers/studio)
- [x] [molecule-polarity 1.3.4-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.4-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.4-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**molecule-shapes 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [molecule-shapes 1.6.7-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.7-rc.1/phet/molecule-shapes_all_phet.html)
- [x] [molecule-shapes 1.6.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.7-rc.1/phet-io/molecule-shapes_all_phet-io.html?phetioStandalone)
- [x] [molecule-shapes 1.6.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.7-rc.1/phet-io/wrappers/studio)
- [x] [molecule-shapes 1.6.7-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.7-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.7-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**molecule-shapes-basics 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [molecule-shapes-basics 1.6.7-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.7-rc.1/phet/molecule-shapes-basics_all_phet.html)
- [x] [molecule-shapes-basics 1.6.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.7-rc.1/phet-io/molecule-shapes-basics_all_phet-io.html?phetioStandalone)
- [x] [molecule-shapes-basics 1.6.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.7-rc.1/phet-io/wrappers/studio)
- [x] [molecule-shapes-basics 1.6.7-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.7-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.7-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**my-solar-system 1.2** (https://github.com/phetsims/scenery/issues/1550)
No phet-io changes, just a separate small bug, please spot check
- [x] [my-solar-system 1.2.5-rc.1](https://phet-dev.colorado.edu/html/my-solar-system/1.2.5-rc.1/phet/my-solar-system_all_phet.html)

**my-solar-system 1.3** (https://github.com/phetsims/sun/issues/864, https://github.com/phetsims/scenery/issues/1550,
https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862, phetioClientRename: phetsims/phet-io#1965)

- [x] [my-solar-system 1.3.0-rc.2](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet/my-solar-system_all_phet.html)
- [x] [my-solar-system 1.3.0-rc.2 phet-io](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet-io/my-solar-system_all_phet-io.html?phetioStandalone)
- [x] [my-solar-system 1.3.0-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet-io/wrappers/studio)
- [x] [my-solar-system 1.3.0-rc.2 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

Combo Box patches (to be checked by QA):
- [x] patch 16: [Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.](https://github.com/phetsims/sun/issues/859#issuecomment-1841866186)
- [x] patch 17: [KeyboardListener bug is likely when listening to 'tab'.](https://github.com/phetsims/sun/issues/864#issuecomment-1863558564)
- [x] patch 18: [focusable bug fix for list box.](https://github.com/phetsims/scenery/issues/1550#issuecomment-1863556922)
- [x] patch 19: [Incorrect default sounds for selecting combo box items](https://github.com/phetsims/sun/issues/861#issuecomment-1863516470)
- [x] patch 20: [Default sound for ComboBoxListBox does not supports dynamic order and visibility of items.](https://github.com/phetsims/sun/issues/862#issuecomment-1863515037)

**natural-selection 1.5** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974, unlinkIndex: phetsims/phet-io#1974, getSimulationURL:
phetsims/phet-io#1974, addSimulationInitializedListener: phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974,
displaySimulation: phetsims/phet-io#1974, setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide:
phetsims/phet-io#1974, getPhetioElementState: phetsims/phet-io#1974, phetioClientRename: phetsims/phet-io#1965)

- [x] [natural-selection 1.5.3-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.5.3-rc.1/phet/natural-selection_all_phet.html)
- [x] [natural-selection 1.5.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.5.3-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.5.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.5.3-rc.1/phet-io/wrappers/studio)
- [x] [natural-selection 1.5.3-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/natural-selection/1.5.3-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/natural-selection/1.5.3-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**ph-scale 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [ph-scale 1.6.10-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.6.10-rc.1/phet/ph-scale_all_phet.html)
- [x] [ph-scale 1.6.10-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.6.10-rc.1/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [x] [ph-scale 1.6.10-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.6.10-rc.1/phet-io/wrappers/studio)
- [x] [ph-scale 1.6.10-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale/1.6.10-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale/1.6.10-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**ph-scale-basics 1.6** (getBasePhetioTypeName, https://github.com/phetsims/phet-io/issues/1974,
getPhetioOverridesFile, https://github.com/phetsims/phet-io/issues/1974, createFromStandardPhetioWrapper:
phetsims/phet-io#1974, getDOMElementID: phetsims/phet-io#1974, SIMULATION_VERSION_STRING: phetsims/phet-io#1974,
phetmarks-perennial-url: phetsims/phet-io#1974, SIMULATION_VERSION_MAJOR_MINOR_STRING1: phetsims/phet-io#1974,
unlinkIndex: phetsims/phet-io#1974, getSimulationURL: phetsims/phet-io#1974, addSimulationInitializedListener:
phetsims/phet-io#1974, launchSimulation: phetsims/phet-io#1974, displaySimulation: phetsims/phet-io#1974,
setSimulationStartedMetadata: phetsims/phet-io#1974, clientGuide: phetsims/phet-io#1974, getPhetioElementState:
phetsims/phet-io#1974, keyboardTraversal:
phetsims/sun#859, https://github.com/phetsims/sun/issues/861, https://github.com/phetsims/sun/issues/862,
phetioClientRename: phetsims/phet-io#1965)

- [x] [ph-scale-basics 1.6.9-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.9-rc.1/phet/ph-scale-basics_all_phet.html)
- [x] [ph-scale-basics 1.6.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.9-rc.1/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [x] [ph-scale-basics 1.6.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.9-rc.1/phet-io/wrappers/studio)
- [x] [ph-scale-basics 1.6.9-rc.1 phet-io Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.9-rc.1/phet-io/)

To be checked by @brent-phet: See https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110 for details for below checkboxes. [Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.9-rc.1/phet-io/).
- [x] Studio: Run script in console from https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110
- [x] Studio: Confirm PhetioEngineIO method doc
- [x] Studio: Confirm IndexedNodeIO method doc (only for sims with an instrumented combo box)
- [x] Wrapper Index: Confirm Client->PhetioClient rename
- [x] API Documentation: Confirm Client->PhetioClient rename on the home page. Please note that many methods for PhetioClient will still refer to `Client` (that is ok)
- [x] API Documentation: Client class is there, but says it is deprecated (and to use PhetioClient)
- [x] API Documentation: PhetioClient class is there, and has methods renamed + deprecated old method (see list in https://github.com/phetsims/phet-io/issues/1974#issuecomment-1863762110)
- [x] PhET-iO Guide: Confirm Client->PhetioClient rename

**Comment by zepumph** [comment]
After discussing with @brent-phet, he and I are going to take on the phet-io specific checks. This means QA only needs to do the combobox checkboxes and the general spot checking checkboxes (I added a spot check for the wrapper index, to briefly click through a few wrappers and make sure they are working well).

**Comment by Nancy-Salpepi** [comment]
OK. Thanks

**Comment by brent-phet** [comment]
@zepumph Should we change `LaunchSimOptions` to `LaunchSimulationOptions` for consistency?

![image](https://github.com/phetsims/qa/assets/127794251/d5fcdec6-62aa-4c10-8a93-5c154cfe21e9)

**Comment by Nancy-Salpepi** [comment]
@zepumph I can't confirm patches 16 and 20 for CaV. The comboboxes are in the simulation and localization tabs of the preferences menu. I don't see any way to hide or reorder items.

**Comment by brent-phet** [comment]
@zepumph I do not see IndexedNodeIO in CaV:

https://phet-dev.colorado.edu/html/center-and-variability/1.1.2-rc.1/phet-io/wrappers/studio/

**Comment by zepumph** [comment]
That is expected. Its ComboBox isn't instrumented. Same reason why https://github.com/phetsims/qa/issues/1017#issuecomment-1868038876 is ok.

**Comment by brent-phet** [comment]
@zepumph I just noticed this one too, so same question? `loadUnbuiltSimVersion` to `loadUnbuiltSimulationVersion`?

<img width="500" alt="image" src="https://github.com/phetsims/qa/assets/127794251/8158646d-0ea3-4b14-b224-d800cb87b7bb">

**Comment by brent-phet** [comment]
FYI - I spot-checked this API JSON, too. 
https://phet-dev.colorado.edu/html/geometric-optics/1.3.4-rc.1/phet-io/geometric-optics-phet-io-api.json

**Comment by zepumph** [comment]
Please make a new issue, loadUnbuiltSimVersion shouldn't be in the doc.

**Comment by brent-phet** [comment]
@zepumph  MSS https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.2/phet-io/wrappers/studio/ 
PhetioEngineIO:
setSimStartedMetadata is NOT marked as deprecated.

**Comment by Nancy-Salpepi** [comment]
@zepumph just wanted to confirm that the spot check I am performing for MSS version 1.2 is to see if shift + tab closes the combobox and moves focus to the item before the combobox? Should the FF warnings be gone from 1.2 or only from 1.3?

**Comment by Nancy-Salpepi** [comment]
QA is done here. Just waiting for a response to https://github.com/phetsims/qa/issues/1017#issuecomment-1874489305.

**Comment by zepumph** [comment]
I don't see checks for NS 1.5. Is that ready? Also I'm assuming unchecked combobox checks are because there isn't a needed feature (like keyboard nav).

**Comment by zepumph** [comment]
>

>. . . for MSS version 1.2 is to see if shift + tab closes the combobox and moves focus to the item before the combobox?

Correct. That was the only patch made

>Should the FF warnings be gone from 1.2 or only from 1.3?

I don't understand what an FF warning is. Is there a paper trail? Also happy to talk.

**Comment by zepumph** [comment]
I spoke with @brent-phet and his checks have been completed and problems fixed in branches.

**Comment by Nancy-Salpepi** [comment]
>Should the FF warnings be gone from 1.2 or only from 1.3?

you had written something earlier in the issue about firefox: https://github.com/phetsims/scenery/issues/1550#issuecomment-1538667990 

I still see all those warnings in 1.2 but not in 1.3.

**Comment by Nancy-Salpepi** [comment]
Sorry! Missed NS! I will do it now.

**Comment by zepumph** [comment]
>you had written something earlier in the issue about firefox: https://github.com/phetsims/scenery/issues/1550#issuecomment-1538667990

Ahh thanks. Yes, that is totally fine, no need to worry about that.

**Comment by Nancy-Salpepi** [comment]
OK done!

**Comment by zepumph** [comment]
Excellent. I'll proceed with deploying. Thanks so much to all testers!
