### ISSUE TITLE
Dev Test: iOS app 1.2(29)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#223]
QA, please test build 29 of the latest iOS app, which is now available in TestFlight.

The issues in the following link should be confirmed: https://github.com/phetsims/phet-ios-app/issues?q=is%3Aissue+is%3Aopen+label%3Astatus%3Afixed-pending-testing.  

Assigning @ariel-phet for priority.

**Comment by KatieWoe** [comment]
Adding priority high as it is a continuation of https://github.com/phetsims/QA/issues/218.  @ariel-phet please change if needed.

**Comment by KatieWoe** [comment]
- [ ] https://github.com/phetsims/phet-ios-app/issues/354
- [ ] https://github.com/phetsims/phet-ios-app/issues/343
- [ ] https://github.com/phetsims/phet-ios-app/issues/338
- [ ] https://github.com/phetsims/phet-ios-app/issues/327
- [ ] https://github.com/phetsims/phet-ios-app/issues/319
- [ ] https://github.com/phetsims/phet-ios-app/issues/342
- [ ] https://github.com/phetsims/phet-ios-app/issues/348
- [ ] https://github.com/phetsims/phet-ios-app/issues/309
- [ ] https://github.com/phetsims/phet-ios-app/issues/328
- [ ] https://github.com/phetsims/phet-ios-app/issues/344
- [ ] https://github.com/phetsims/phet-ios-app/issues/328
- [ ] https://github.com/phetsims/phet-ios-app/issues/351
- [ ] https://github.com/phetsims/phet-ios-app/issues/388
- [ ] https://github.com/phetsims/phet-ios-app/issues/386
- [ ] https://github.com/phetsims/phet-ios-app/issues/346
- [ ] https://github.com/phetsims/phet-ios-app/issues/353

**Comment by ariel-phet** [comment]
Looks like this can be current top priority

**Comment by KatieWoe** [comment]
@chris-huxtable Are the buttons that change the view complete in this version?

**Comment by lmulhall-phet** [comment]
I'm still seeing https://github.com/phetsims/phet-ios-app/issues/353 on my iPhone SE. Also seeing some jumpy scrolling (https://github.com/phetsims/phet-ios-app/issues/309) on iPad Air running iOS 11.4.1 after the app has been open for a while.

**Comment by chris-huxtable** [comment]
@KatieWoe - They are not. I will be implementing the TableView in v1.2(30)

**Comment by KatieWoe** [comment]
@chris-huxtable I'm sometimes noticing a bit of a delay when tapping the switch that turns off favorites.  I've also noticed that tapping to open the filter menu doesn't always respond, possibly due to a small target.  Are either of these issue worthy for you?

**Comment by chris-huxtable** [comment]
The favourites issue is due to the search system. There is not much I can do about that without a ton of work which would have to be decided by @ariel-phet and @oliver-phet. I can try* to increase the size of the filter button, but it would definitely be 'non-standard' @ariel-phet or @oliver-phet, what do you think?

**Comment by KatieWoe** [comment]
The issues to confirm have been looked at.  Either they are confirmed and closed, or are left open for reasons discussed in the issues themselves.  Testing will continue to search for new bugs.  @chris-huxtable let me know if you see anything that was missed or if you think something discussed in an issue deserves its own issue.

**Comment by chris-huxtable** [comment]
I have pushed a new tagged commit of v1.2(30)

**Comment by KatieWoe** [comment]
For QA Team.  Issues to test and confirm in v1.2(30).  @chris-huxtable let me know if you notice any missing or want anything added.  Checked off means confirmed.  Bolded means still an issue or unable to confirm.
---
- [ ] https://github.com/phetsims/phet-ios-app/issues/413
- [ ] https://github.com/phetsims/phet-ios-app/issues/405
- [ ] https://github.com/phetsims/phet-ios-app/issues/404
- [ ] https://github.com/phetsims/phet-ios-app/issues/403
- [ ] https://github.com/phetsims/phet-ios-app/issues/402
- [ ] https://github.com/phetsims/phet-ios-app/issues/400
- [ ] https://github.com/phetsims/phet-ios-app/issues/397
- [ ] https://github.com/phetsims/phet-ios-app/issues/390
- [ ] https://github.com/phetsims/phet-ios-app/issues/385
- [ ] https://github.com/phetsims/phet-ios-app/issues/384
- [ ] https://github.com/phetsims/phet-ios-app/issues/350
- [ ] https://github.com/phetsims/phet-ios-app/issues/337
- [ ] https://github.com/phetsims/phet-ios-app/issues/337

**Comment by mattpen** [comment]
@KatieWoe - V1.2(30) is now up on TestFlight.  Should we open a new issue?

**Comment by mattpen** [comment]
Build 1.2(29) has been expired.

**Comment by KatieWoe** [comment]
We can if you'd like.  If you do, please include the checklist I made above in the issue, along with any other issues that you want tested.

**Comment by mattpen** [comment]
Lets test build 30 in https://github.com/phetsims/QA/issues/225
