### ISSUE TITLE
RC testing for Decaf Faraday 1.0.0-dev.17

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#494]
In https://github.com/phetsims/decaf/issues/50, we deployed a dev version of Decaf/Faraday, and it should be tested as if it were an RC.  There are 4 simulations in this batch.  The links are here:

https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.17/?simulation=faraday
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.17/?simulation=magnet-and-compass
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.17/?simulation=magnets-and-electromagnets
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.17/?simulation=generator

Locales are from this list:

```

am
ar
be
bg
bs
ca
cs
da
de
el
es
es_MX
es_PE
et
eu
fa
fi
fr
gl
hr
ht
hu
hy
in
it
iw
ja
ka
kk
km
kn
ko
ku_TR
lo
lt
lv
mk
mn
mr
nl
pl
pt
pt_BR
ro
ru
sk
sl
sq
sr
sv
th
tk
tr
uk
vi
zh_CN
zh_TW
```

You can append `&locale=...` to test a locale.

This is a candidate for release, so should be tested on our supported platforms.  This is our first RC test for decaf simulations, so I'm not 100% certain of the process or which platforms we will ultimately support.

@ariel-phet anything else for this issue?  Please prioritize and delegate.  Also, let me know if we should create a new RC task template for decaf.

**Comment by KatieWoe** [comment]
[Testing Matrix](https://docs.google.com/spreadsheets/d/1-7Py_E8C-MVr3g7ZNFmxubcyebuAzP-kdOr0MDtZMIc/edit#gid=878453071)
Normal Query parameters for rcs are not available. Check the locales instead of string tests. Note that there are 4 pages in the test matrix, one for each sim.

**Comment by ariel-phet** [comment]
@KatieWoe the first simulation link should receive the majority of focus at first, since other simulations are derivative.

**Comment by ariel-phet** [comment]
@KatieWoe @samreid I just tested on Windows 10, latest chrome.

@samreid - it looks like you have made a change where the sim opens at the browser window size, although that is nice in theory it absolutely TANKS performance for me.

At the default Java size, things are smooth and nice on chrome, at full screen size the sim is barely useable.

**Comment by samreid** [comment]
If you reduce the browser window size manually, does the performance improve?

**Comment by ariel-phet** [comment]
@samreid yes...if I reload the sim in the smaller window

**Comment by KatieWoe** [comment]
Confirming that behavior seen by @ariel-phet in https://github.com/phetsims/QA/issues/494#issuecomment-613623340 seems to happen on Edge as well. I'm not too worried about it, as the performance still seems to have little if any impact on pedagogy. Seems similar to the behavior described in https://github.com/phetsims/decaf/issues/51. If we still want full screen use, it may be useful to have an alert saying that performance can be better by loading in a smaller window.

**Comment by samreid** [comment]
For https://github.com/phetsims/decaf/issues/68 I published https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.20/index.html 

No testing needs to be redone, but can future testing be done on dev.20?

**Comment by kathy-phet** [comment]
@samreid - I am still having some loading cut off when loading in landscape on iPhone in dev.20. Can you work locally with your devices to see if you can debug to something that does not cut off the bottom on load?

**Comment by ariel-phet** [comment]
@samreid testing is basically done here (the "spin off" sims are getting more testing as part of the main decaf testing issue)

Would you like this issue to remain open as a summary of found issues? If not, feel free to close.

**Comment by samreid** [comment]
Thanks for the testing @KatieWoe and team, this can be closed.
